### PR TITLE
less dom reads

### LINKED ISSUE #329: Move viewport to state
Currently we call `getViewport` all over the place to get the current viewport. This was done for simplicity and because when keyboard dragging we ignored window scrolling... 

This is a non-functional issue. It just feels wrong to have state functions reaching to the window to grab it's current state. Ideally we would just store the `viewport` in the state while dragging and update it when a window scroll occurs.

We do not need to worry about it changing dimensions as we cancel a drag on any resize.

### PR DESCRIPTION
**Pull request by alexreardon**
Closes #329.

Fixing a minor performance regressed in lifting big data sets with our new auto scroller.

What this PR does:

- avoids independent calls to functions that request values from the window from the `state` folder (engineering health)
- Fixes minor perf regression on lift. This was caused by reading window properties at bad times in an animation frame. There were a few ways around it. But this method gets around the problem while also doing something we wanted to anyway.

The code changes in `src` are super basic. There was some more heavy lifting required to get everything working in the tests. Previously tests were setting viewport properties in anticipation of the viewport being read. Now these properties can be passed directly to functions

### CODE REVIEW

File: src/state/auto-scroller/can-scroll.js [hunk 1]
```diff
@@ -94,38 +91,12 @@ export const canPartiallyScroll = ({
...
-  if (!el) {
-    return origin;
-  }
-
-  const viewport: Area = getViewport();
-
-  // window.innerWidth / innerHeight includes scrollbar
-  // however the scrollHeight / scrollWidth do not :(
-
-  const maxScroll: Position = getMaxScroll({
```
Comment (alexreardon) [inline src/state/auto-scroller/can-scroll.js]: this is now computed in getViewport

File: src/state/debug-middleware/timing-average-middleware.js [hunk 2]
```diff
@@ -0,0 +1,46 @@
+// @flow
```
Comment (alexreardon) [inline src/state/debug-middleware/timing-average-middleware.js]: another debug middleware - this one averages the time taken for actions and prints a result

File: src/state/move-cross-axis/get-best-cross-axis-droppable.js [hunk 3]
```diff
@@ -49,8 +51,6 @@ export default ({
     sourceClipped[axis.start],
     sourceClipped[axis.end]
   );
-  const viewport: Area = getViewport();
```
Comment (alexreardon) [inline src/state/move-cross-axis/get-best-cross-axis-droppable.js]: that's what i'm talking about 👍

File: src/state/move-to-next-index/in-foreign-list.js [hunk 4]
```diff
@@ -74,7 +73,6 @@ export default ({
     return 'start';
   })();
 
-  const viewport: Area = getViewport();
```
Comment (alexreardon) [inline src/state/move-to-next-index/in-foreign-list.js]: goodbye old friend

File: src/state/reducer.js [hunk 5]
```diff
@@ -478,22 +481,23 @@ export default (state: State = clean('IDLE'), action: Action): State => {
...
+    const { viewport } = action.payload;
     const drag: ?DragState = state.drag;
 
     if (!drag) {
       console.error('cannot move with window scrolling if no current drag');
       return clean();
     }
 
-    if (isEqual(windowScroll, drag.current.windowScroll)) {
+    // TODO: need to improve this so that it compares the whole viewport
```
Comment (alexreardon) [inline src/state/reducer.js]: I think this check is good enough for now

File: src/view/draggable/draggable.jsx [hunk 6]
```diff
@@ -13,7 +13,7 @@ import type {
 import DraggableDimensionPublisher from '../draggable-dimension-publisher/';
 import Moveable from '../moveable/';
 import DragHandle from '../drag-handle';
-import getWindowScroll from '../../window/get-window-scroll';
+import getViewport from '../window/get-viewport';
```
Comment (alexreardon) [inline src/view/draggable/draggable.jsx]: this is now the only thing that publishes the viewport into the state

File: src/view/window/get-viewport.js [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+  // Computed
+  const right: number = left + width;
+  const bottom: number = top + height;
+
+  const subject: Area = getArea({
+    top, left, right, bottom,
+  });
+
+  const maxScroll: Position = getMaxScroll({
+    scrollHeight: doc.scrollHeight,
```
Comment (alexreardon) [inline src/view/window/get-viewport.js]: It turns out these properties are super slow to read sometimes

File: stories/src/horizontal/author-app.jsx [hunk 8]
```diff
@@ -49,6 +49,10 @@ export default class AuthorApp extends Component<Props, State> {
       return;
     }
 
+    if (result.destination.index === result.source.index) {
```
Comment (alexreardon) [inline stories/src/horizontal/author-app.jsx]: A little optimisation for our storybooks

File: test/unit/integration/lift-action-and-dimension-marshal.spec.js [hunk 9]
```diff
@@ -30,7 +33,18 @@ import type {
 } from '../../../src/types';
 
 const preset = getPreset();
-const origin: Position = { x: 0, y: 0 };
+
+const scrolledViewport: Viewport = createViewport({
```
Comment (alexreardon) [inline test/unit/integration/lift-action-and-dimension-marshal.spec.js]: much clearer now

File: test/unit/state/auto-scroll/jump-scroller.spec.js [hunk 10]
```diff
@@ -25,18 +24,22 @@ const windowScrollSize = {
...
+  scrollWidth: windowScrollSize.scrollWidth,
+  scroll: origin,
 });
 
-const disableWindowScroll = () => {
-  setWindowScrollSize({
-    scrollHeight: viewport.height,
-    scrollWidth: viewport.width,
-  });
+const unscrollableViewport: Viewport = {
```
Comment (alexreardon) [inline test/unit/state/auto-scroll/jump-scroller.spec.js]: yum

File: test/utils/viewport.js [hunk 11]
```diff
@@ -0,0 +1,110 @@
+// @flow
```
Comment (alexreardon) [inline test/utils/viewport.js]: improved helpers
