### PR TITLE
hook functions are now called after the reducer

### LINKED ISSUE #617: Error when updating state inside onDragStart
I'm calling setState inside onDragStart and I'm getting the following error:

`Error: Invariant failed: Attempting to move in an unsupported phase PREPARING`

### What version of `React` are you using?

16.3.2

### What version of `react-beautiful-dnd` are you running?

8.0.1

### What browser are you using?

Chrome

### PR DESCRIPTION
**Pull request by alexreardon**
Fixes #617

### CODE REVIEW

File: src/view/draggable/draggable.jsx [hunk 1]
```diff
@@ -115,15 +117,6 @@ export default class Draggable extends Component<Props> {
     this.ref = null;
   }
 
-  // This should already be handled gracefully in DragHandle.
```
Comment (alexreardon) [inline src/view/draggable/draggable.jsx]: this is already taken care of inside of the drag-handle and the reducer

**Comment by alexreardon** [comment]
This brings the behaviour back in line with previous versions

**Comment by alexreardon** [comment]
Super helpful: https://allyjs.io/tutorials/focusing-in-svg.html

**Comment by alexreardon** [comment]
IE11 will not support .focus() on an SVG. This means if you are dragging an SVG in ie11:

- portals will not work (we need to restore focus after the element moves to the portal)
- focus will not be retained when moving between lists

Right now both of these will throw an exception in IE11 (same for 7.1.3)

I am not sure what the best path forward is. We could either make a note of it and provide some tips, or we could continue to block the use of SVG's as drag handles as we are now... 🤔
