### PR TITLE
fixing issue with announcer and hot module reloading

### LINKED ISSUE #1584: Invariant failed: Announcement node already mounted
### Expected behavior
There should be no such warnings in the console.

### Actual behavior
After HMR update, react-beautiful-dnd throws error that is catched by it's error boundary. Error is throwed on every update, no matter if updated Component is inside or outside DragDropContext.

### What version of `React` are you using?
16.11.0

### What version of `react-beautiful-dnd` are you running?
12.0.0

### What browser are you using?
Google Chrome 78.0.3904.8

### PR DESCRIPTION
**Pull request by alexreardon**
Closes #1584

### CODE REVIEW

File: src/view/use-announcer/use-announcer.js [hunk 1]
```diff
@@ -14,42 +14,46 @@ export default function useAnnouncer(contextId: ContextId): Announce {
...
-      // during a mount be published
-      setTimeout(function remove() {
+      return function cleanup() {
+        // grabbing and clearing ref incase effect is about to run again
         const toBeRemoved: ?HTMLElement = ref.current;
         invariant(toBeRemoved, 'Cannot unmount announcement node');
-
-        // Remove from body
-        getBodyElement().removeChild(toBeRemoved);
         ref.current = null;
```
Comment (alexreardon) [inline src/view/use-announcer/use-announcer.js]: this is the fix here. Clearing the ref before the timeout

File: docs/support/media.md [hunk 2]
```diff
@@ -30,6 +30,7 @@ This page contains a list of articles, blogs and newsletters that `react-beautif
 
 ## Newsletters
 
+- Tiny letter [November 04, 2019](https://tinyletter.com/cassidoo/letters/the-world-is-changed-by-your-example-not-by-your-opinion-paulo-coelho)
```
Comment (alexreardon) [inline docs/support/media.md]: unrelated :D
