### PR TITLE
fixing invariant check in reducer. Fixes #617

### LINKED ISSUE #617: Error when updating state inside onDragStart
I'm calling setState inside onDragStart and I'm getting the following error:

`Error: Invariant failed: Attempting to move in an unsupported phase PREPARING`

### What version of `React` are you using?

16.3.2

### What version of `react-beautiful-dnd` are you running?

8.0.1

### What browser are you using?

Chrome

### PR DESCRIPTION
**Pull request by alexreardon**
Fixes #617

### CODE REVIEW

File: src/state/reducer.js [hunk 1]
```diff
@@ -332,10 +332,9 @@ export default (state: State = idle, action: Action): State => {
     }
 
     invariant(
-      target.isEnabled === isEnabled,
-      `Trying to set droppable isEnabled to ${String(
-        isEnabled,
-      )} but it is already ${String(isEnabled)}`,
+      target.isEnabled !== isEnabled,
```
Comment (alexreardon) [inline src/state/reducer.js]: this invariant check was the wrong way around.

We need to throw if they are the same.

Comment (alexreardon) [reply src/state/reducer.js]: We need these values to be different - otherwise it is an error
